exclude: 'public/vendor/'
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: trailing-whitespace

  - repo: https://github.com/InfinityFreeHosting/pre-commit-php
    rev: 1.3.1
    hooks:
      - id: php-lint
#      - id: php-cs
#      - id: php-cbf
      - id: php-cs-fixer
        args:
          - --config=.php-cs-fixer.php

  - repo: local
    hooks:
      - id: phpstan-analyse
        name: PHPStan Analyse
        entry: ./vendor/bin/phpstan analyse --no-progress --error-format=raw
        language: system
        files: ^src/
        always_run: true
